#include <keyboard.h>

// row defs
GPIO_TypeDef* row_ports[ROWS] = {ROW_1_GPIO_Port, ROW_2_GPIO_Port, ROW_3_GPIO_Port, ROW_4_GPIO_Port, ROW_5_GPIO_Port};
uint16_t row_pins[ROWS] = {ROW_1_Pin, ROW_2_Pin, ROW_3_Pin, ROW_4_Pin, ROW_5_Pin};
// col defs
GPIO_TypeDef* col_ports[COLS] = {COL_0_GPIO_Port, COL_1_GPIO_Port, COL_2_GPIO_Port, COL_3_GPIO_Port,
                                 COL_4_GPIO_Port, COL_5_GPIO_Port, COL_6_GPIO_Port, COL_7_GPIO_Port,
                                 COL_8_GPIO_Port, COL_9_GPIO_Port, COL_10_GPIO_Port, COL_11_GPIO_Port,
                                 COL_12_GPIO_Port, COL_13_GPIO_Port, COL_14_GPIO_Port, COL_15_GPIO_Port}; 
uint16_t col_pins[COLS] = {COL_0_Pin, COL_1_Pin, COL_2_Pin, COL_3_Pin,
                           COL_4_Pin, COL_5_Pin, COL_6_Pin, COL_7_Pin,
                           COL_8_Pin, COL_9_Pin, COL_10_Pin, COL_11_Pin,
                           COL_12_Pin, COL_13_Pin, COL_14_Pin, COL_15_Pin}; 


const uint8_t keymap[ROWS][COLS] = {
    // Row 0
    {HID_KEY_PAUSE, HID_KEY_ESCAPE, HID_KEY_F1, HID_KEY_F2, HID_KEY_F3, HID_KEY_F4, HID_KEY_F5, HID_KEY_F6, HID_KEY_F7, 
        HID_KEY_F8, HID_KEY_F9, HID_KEY_F10, HID_KEY_F11, HID_KEY_F12, HID_KEY_NONE, HID_KEY_NONE },
    // Row 1
    {HID_KEY_NONE, HID_KEY_GRAVE, HID_KEY_1, HID_KEY_2, HID_KEY_3, HID_KEY_4, HID_KEY_5, HID_KEY_6, HID_KEY_7,
        HID_KEY_8, HID_KEY_9, HID_KEY_0, HID_KEY_MINUS, HID_KEY_EQUAL, HID_KEY_BACKSPACE, HID_KEY_DELETE }, 
    // Row 2
    {HID_KEY_NONE, HID_KEY_TAB, HID_KEY_Q, HID_KEY_W, HID_KEY_E, HID_KEY_R, HID_KEY_T, HID_KEY_Y, HID_KEY_U,
        HID_KEY_I, HID_KEY_O, HID_KEY_P, HID_KEY_BRACKET_LEFT, HID_KEY_BRACKET_RIGHT, HID_KEY_BACKSLASH, HID_KEY_PAGE_UP },
    // Row 3
    {HID_KEY_NONE, HID_KEY_CAPS_LOCK, HID_KEY_A, HID_KEY_S, HID_KEY_D, HID_KEY_F, HID_KEY_G, HID_KEY_H, HID_KEY_J,
        HID_KEY_K, HID_KEY_L, HID_KEY_SEMICOLON, HID_KEY_APOSTROPHE, HID_KEY_ENTER, HID_KEY_NONE, HID_KEY_PAGE_DOWN },
    // Row 4
    {HID_KEY_NONE, HID_KEY_SHIFT_LEFT, HID_KEY_Z, HID_KEY_X, HID_KEY_C, HID_KEY_V, HID_KEY_B, HID_KEY_N, HID_KEY_M,
        HID_KEY_COMMA, HID_KEY_PERIOD, HID_KEY_SLASH, HID_KEY_SHIFT_RIGHT, HID_KEY_NONE, HID_KEY_ARROW_UP, HID_KEY_INSERT },
    // Row 5
    {HID_KEY_NONE, HID_KEY_CONTROL_LEFT, HID_KEY_GUI_LEFT, HID_KEY_ALT_LEFT, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_SPACE, HID_KEY_NONE,
        HID_KEY_NONE, HID_KEY_NONE, HID_KEY_ALT_RIGHT, HID_KEY_CONTROL_RIGHT, HID_KEY_NONE, HID_KEY_ARROW_LEFT, HID_KEY_ARROW_DOWN, HID_KEY_ARROW_RIGHT}
};